// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP4Pf57_QlNXAIqEATap0t9JRzuBfbIa0',
    appId: '1:546893861837:web:d0e75397e1f623006a2a84',
    messagingSenderId: '546893861837',
    projectId: 'flutterdemo-fa9b2',
    authDomain: 'flutterdemo-fa9b2.firebaseapp.com',
    storageBucket: 'flutterdemo-fa9b2.appspot.com',
    measurementId: 'G-2SH4S4NWYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXQha1RENrDR-s5J-4n9we13HU_PPMd_o',
    appId: '1:546893861837:android:112a5d7569d857746a2a84',
    messagingSenderId: '546893861837',
    projectId: 'flutterdemo-fa9b2',
    storageBucket: 'flutterdemo-fa9b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkR6jQkw6UK1-fXAdswS6psuCbm2IYHag',
    appId: '1:546893861837:ios:af20f5efe853044c6a2a84',
    messagingSenderId: '546893861837',
    projectId: 'flutterdemo-fa9b2',
    storageBucket: 'flutterdemo-fa9b2.appspot.com',
    iosClientId: '546893861837-62rte7rgg8he9u8t0c8f1umdn0t2f719.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkR6jQkw6UK1-fXAdswS6psuCbm2IYHag',
    appId: '1:546893861837:ios:af20f5efe853044c6a2a84',
    messagingSenderId: '546893861837',
    projectId: 'flutterdemo-fa9b2',
    storageBucket: 'flutterdemo-fa9b2.appspot.com',
    iosClientId: '546893861837-62rte7rgg8he9u8t0c8f1umdn0t2f719.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebaseAuth',
  );
}
